// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvcijqJR893sCTq3jy5QppK-iyEyq81PU',
    appId: '1:272357624227:web:c00e72c2128359638c3216',
    messagingSenderId: '272357624227',
    projectId: 'hr-portal-8317c',
    authDomain: 'hr-portal-8317c.firebaseapp.com',
    storageBucket: 'hr-portal-8317c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQtbjnJYZgvU1luB0hzDxe3eq9rUYRX-c',
    appId: '1:272357624227:android:47d28fb3205209748c3216',
    messagingSenderId: '272357624227',
    projectId: 'hr-portal-8317c',
    storageBucket: 'hr-portal-8317c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6LYfrqBCsfZMWo5Nd9mwXLUN3mbR0O7A',
    appId: '1:272357624227:ios:4c67be1b9c9155348c3216',
    messagingSenderId: '272357624227',
    projectId: 'hr-portal-8317c',
    storageBucket: 'hr-portal-8317c.firebasestorage.app',
    iosBundleId: 'com.newhorizon.hr.hrPortal',
  );

}