name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build web (PROD)
        run: flutter build web --release --dart-define=FLAVOR=dev --base-href "/hrportal/"

      # مهم جدًا لـ GoRouter على GitHub Pages:
      - name: Add 404.html for SPA routing
        run: cp build/web/index.html build/web/404.html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web